proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m inactive=60m use_temp_path=off;

server {
    listen 80;

    location / {
        proxy_pass http://flask_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Настройка кеширования Nginx
        proxy_cache my_cache;
        proxy_cache_valid 200 1m; # Кешируем успешные ответы на 1 минуту
        add_header X-Cache-Status $upstream_cache_status; # Показывает HIT или MISS в заголовках
    }
}